src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use DateTime;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class User implements UserInterface
{
    const STATUS_VOLUNTEER = 'volunteer';
    const STATUS_BENEFICIARY = 'beneficiary';
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $mobicoopId;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActive;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity=ScheduleVolunteer::class, mappedBy="user")
     */
    private $scheduleVolunteers;

    /**
     * @ORM\OneToMany(targetEntity=Trip::class, mappedBy="volunteer")
     */
    private $tripsVolunteer;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\OneToMany(targetEntity=Trip::class, mappedBy="beneficiary", orphanRemoval=true)
     */
    private $trips;

    private $givenName;

    private $familyName;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updateAt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $profilePicture;

    public function __construct()
    {
        $this->trips = new ArrayCollection();
        $this->scheduleVolunteers = new ArrayCollection();
        $this->tripsVolunteer = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMobicoopId(): ?int
    {
        return $this->mobicoopId;
    }

    public function setMobicoopId(int $mobicoopId): self
    {
        $this->mobicoopId = $mobicoopId;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->createdAt;
    }

    /**
     * @ORM\PrePersist
     * @return $this
     */
    public function setCreatedAt(): self
    {
        $this->createdAt = new DateTime();

        return $this;
    }

    public function getUpdatedAt(): ?DateTimeInterface
    {
        return $this->updatedAt;
    }

    /**
     * @ORM\PreUpdate()
     * @return $this
     */
    public function setUpdatedAt(): self
    {
        $this->updatedAt = new DateTime();

        return $this;
    }

    /**
     * @return Collection|ScheduleVolunteer[]
     */
    public function getScheduleVolunteers(): Collection
    {
        return $this->scheduleVolunteers;
    }

    public function addScheduleVolunteer(ScheduleVolunteer $scheduleVolunteer): self
    {
        if (!$this->scheduleVolunteers->contains($scheduleVolunteer)) {
            $this->scheduleVolunteers[] = $scheduleVolunteer;
            $scheduleVolunteer->setUser($this);
        }

        return $this;
    }

    public function removeScheduleVolunteer(ScheduleVolunteer $scheduleVolunteer): self
    {
        if ($this->scheduleVolunteers->contains($scheduleVolunteer)) {
            $this->scheduleVolunteers->removeElement($scheduleVolunteer);
            // set the owning side to null (unless already changed)
            if ($scheduleVolunteer->getUser() === $this) {
                $scheduleVolunteer->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Trip[]
     */
    public function getTripsVolunteer(): Collection
    {
        return $this->tripsVolunteer;
    }

    public function addTripsVolunteer(Trip $tripsVolunteer): self
    {
        if (!$this->tripsVolunteer->contains($tripsVolunteer)) {
            $this->tripsVolunteer[] = $tripsVolunteer;
            $tripsVolunteer->setVolunteer($this);
        }

        return $this;
    }

    public function removeTripsVolunteer(Trip $tripsVolunteer): self
    {
        if ($this->tripsVolunteer->contains($tripsVolunteer)) {
            $this->tripsVolunteer->removeElement($tripsVolunteer);
            // set the owning side to null (unless already changed)
            if ($tripsVolunteer->getVolunteer() === $this) {
                $tripsVolunteer->setVolunteer(null);
            }
        }

        return $this;
    }

    public function getRoles()
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER_VOLUNTEER';

        return array_unique($roles);
    }

    public function setRoles(array $roles)
    {
        $this->roles = $roles;
    }

    public function getPassword()
    {
        // Not used
    }

    public function getSalt()
    {
        // Not used
    }

    public function getUsername()
    {
        return $this->mobicoopId;
    }

    public function eraseCredentials()
    {
        // Not used
    }

    /**
     * @return Collection|Trip[]
     */
    public function getTrips(): Collection
    {
        return $this->trips;
    }

    public function addTrip(Trip $trip): self
    {
        if (!$this->trips->contains($trip)) {
            $this->trips[] = $trip;
            $trip->setBeneficiary($this);
        }

        return $this;
    }

    public function removeTrip(Trip $trip): self
    {
        if ($this->trips->contains($trip)) {
            $this->trips->removeElement($trip);
            // set the owning side to null (unless already changed)
            if ($trip->getBeneficiary() === $this) {
                $trip->setBeneficiary(null);
            }
        }

        return $this;
    }

    public function getGivenName()
    {
        return $this->givenName;
    }

    public function setGivenName($givenName)
    {
        $this->givenName = $givenName;

        return $this;
    }

    public function getFamilyName()
    {
        return $this->familyName;
    }

    public function setFamilyName($familyName)
    {
        $this->familyName = $familyName;

        return $this;
    }

    public function getUpdateAt(): ?DateTimeInterface
    {
        return $this->updateAt;
    }

    public function setUpdateAt(DateTimeInterface $updateAt): self
    {
        $this->updateAt = $updateAt;

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->profilePicture;
    }

    public function setProfilePicture(?string $profilePicture): self
    {
        $this->profilePicture = $profilePicture;

        return $this;
    }
}

templates/_arab_templates/ar_trip_form.html.twig
{{ form_start(form) }}
    {{ form_row(form.date) }}
<div class="row pl pr pb mb">
    <div class="trip-row col s10">
        {{ form_row(form.departure) }}
    </div>
    <i class="material-icons pictos-trip pt col s1 offset-s1">gps_fixed</i>
</div>
<div class="row pl pr">
    <div class="trip-row col s10">
        {{ form_row(form.arrival) }}
    </div>
    <i class="material-icons pictos-trip pt col s1 offset-s1">location_on</i>
</div>
<div class="center-align">
    <button class="btn waves-effect waves-light mt mb" id="button_schedule" type="submit" name="action">
        <i class="material-icons">check</i>
    </button>
</div>
{{ form_end(form) }}

templates/_arab_templates/ar_trip_show.html.twig
<table class="table table-trip col s10 offset-s1">
    <tbody>
    <tr>
        <th class="left-align pl">
            {{ trip.date|date('Y-m-d') }}
        </th>
        <td>
            <i class="material-icons small pt-s pr">date_range</i>
        </td>
    </tr>
    <tr>
        <th class="left-align pl">
            {{ trip.date|date('h:i A') }}
        </th>
        <td>
            <i class="material-icons small pt-s pr">access_time</i>
        </td>
    </tr>
    <tr>
        <th class="left-align pl">
            {{ trip.departure.name }}
        </th>
        <td>
            <i class="material-icons small pt-s pr">gps_fixed</i>
        </td>
    </tr>
    <tr>
        <th class="left-align pl">
            {{ trip.arrival.name }}
        </th>
        <td>
            <i class="material-icons small pt-s pr">location_on</i>
        </td>
    </tr>
    {% if trip.volunteer and app.user.status == 'beneficiary' %}
        <tr>
            <th class="left-align pl">
                <a class="waves-effect waves-light modal-trigger" href="#userInfo">
                    {{ volunteer.givenName }} {{ volunteer.familyName }}
                </a>
            </th>
            <td>
                <i class="material-icons small pt-s pr">people</i>
            </td>
        </tr>
    {% endif %}
    {% if app.user.status == 'volunteer' %}
        <tr>
            <th class="left-align pl">
                <a class="waves-effect waves-light modal-trigger" href="#userInfo">
                    {{ beneficiary.givenName }} {{ beneficiary.familyName }}
                </a>
            </th>
            <td>
                <i class="material-icons small pt-s pr">people</i>
            </td>
        </tr>
    {% endif %}
    </tbody>
</table>

templates/_arab_templates/ar_user_edit_form.html.twig
{{ form_start(form) }}
<div class="row pl pr mt">
    <div class="col s10 pl pr mb">
        {{ form_row(form.givenName, {'attr': {'value': user.givenName }}) }}
    </div>
    <i class="material-icons pictos-trip col s1 offset-s1 pt">person_pin</i>
</div>
<div class="row pl pr mb-l">
    <div class="col s10 pl pr mb">
        {{ form_row(form.familyName, {'attr': {'value': user.familyName }}) }}
    </div>
    <i class="material-icons pictos-trip col s1 offset-s1 pt">person_pin</i>
</div>
<div class="row pl pr mb-l">
    <div class="col s10 pl pr mb">
        {{ form_row(form.email, {'attr': {'value': user.email }}) }}
    </div>
    <i class="material-icons pictos-trip col s1 offset-s1 pt">mail</i>
</div>
<div class="row pl pr mb-l">
    <div class="col s10 pl pr mb">
        {{ form_row(form.telephone, {'attr': {'value': user.telephone }}) }}
    </div>
    <i class="material-icons pictos-trip col s1 offset-s1 pt">phone</i>
</div>
<div class="row pl pr mb-l">
    <i class="material-icons pictos-trip col s1 pt">lock</i>
    <div class="col s10 offset-s1 pl pr mb">
        {{ form_row(form.password, {'attr': {'value': user.password }}) }}
    </div>
</div>
<div class="row pl pr mb-l">
    <i class="material-icons pictos-trip col s1 pt">lock</i>
    <div class="col s10 offset-s1 pl pr mb">
        {{ form_row(form.confirm_password) }}
    </div>
</div>
<div class="row pl pr mb-l" hidden>
    <i class="material-icons pictos-trip col s1 pt">person_pin</i>
    <div class="col s10 offset-s1 pl pr mb">
        {{ form_widget(form.gender) }}
    </div>
</div>
<div class="row pl pr mb-l" hidden>
    <i class="material-icons pictos-trip col s1 pt">person_pin</i>
    <div class="col s10 offset-s1 pl pr mb">
        {{ form_widget(form.status) }}
    </div>
</div>
<div class="row pl pr mb-l" hidden>
    <i class="material-icons pictos-trip col s1 pt">cake</i>
    <div class="col s10 offset-s1 pl pr mb">
        {{ form_row(form.birthDate, {'attr': {'value': user.birthDate }}) }}
    </div>
</div>
{{ form_rest(form) }}
<div class="center-align mb">
    <button class="btn"><i class="material-icons">arrow_forward</i></button>
</div>
{{ form_end(form) }}

templates/_arab_templates/ar_user_login_form.html.twig
{{ form_start(form) }}
<div class="row pl pr pb-l">
    <div class="pl pr schedule-date col s10">
        {{ form_widget(form.email) }}
    </div>
    <i class="material-icons pictos-trip pt col s1 offset-s1">email</i>
</div>
<div class="row pl pr pb-l">
    <div class="pl pr schedule-date col s10">
        {{ form_widget(form.password) }}
    </div>
    <i class="material-icons pictos-trip pt col s1 offset-s1">lock</i>
</div>
<div class="center-align">
    <button class="btn"><i class="material-icons">arrow_forward</i></button>
</div>
{{ form_end(form) }}

templates/_arab_templates/ar_user_register_form.html.twig
{{ form_start(form) }}
<div class="row pl pr mt">
    <div class="col s10 pl pr mb">
        {{ form_widget(form.givenName) }}
    </div>
    <i class="material-icons pictos-trip col s1 offset-s1 pt">person_pin</i>
</div>
<div class="row pl pr mb-l">
    <div class="col s10 pl pr mb">
        {{ form_widget(form.familyName) }}
    </div>
    <i class="material-icons pictos-trip col s1 offset-s1 pt">person_pin</i>
</div>
<div class="row pl pr mb-l">
    <div class="col s10 pl pr mb">
        {{ form_widget(form.email) }}
    </div>
    <i class="material-icons pictos-trip col s1 offset-s1 pt">mail</i>
</div>
<div class="row pl pr mb-l">
    <div class="col s10 pl pr mb">
        {{ form_widget(form.status) }}
    </div>
    <i class="material-icons pictos-trip pt col s1 offset-s1 pt">person_pin</i>
</div>
<div class="row pl pr mb-l">
    <div class="col s10 pl pr mb">
        {{ form_widget(form.password) }}
    </div>
    <i class="material-icons pictos-trip col s1 offset-s1 pt">lock</i>
</div>
<div class="row pl pr mb-l">
    <div class="col s10 pl pr mb">
        {{ form_widget(form.confirm_password) }}
    </div>
    <i class="material-icons pictos-trip col s1 offset-s1 pt">lock</i>
</div>
<div class="row pl pr mb-l">
    <div class="col s10 pl pr mb">
        {{ form_widget(form.telephone) }}
    </div>
    <i class="material-icons pictos-trip col s1 offset-s1 pt">phone</i>
</div>
<div class="row pl pr mb-l">
    <div class="col s10 pl pr mb">
        {{ form_widget(form.gender) }}
    </div>
    <i class="material-icons pictos-trip col s1 offset-s1 pt">person_pin</i>
</div>
<div class="row pl pr mb-l">
    <div class="col s10 pl pr mb">
        {{ form_widget(form.birthDate) }}
    </div>
    <i class="material-icons pictos-trip col s1 offset-s1 pt">cake</i>
</div>
<div class="center-align mb">
    <button class="btn"><i class="material-icons">arrow_forward</i></button>
</div>
{{ form_end(form) }}

templates/_arab_templates/ar_user_show.html.twig
<table class="table table-trip col s10 offset-s1">
    <tbody>
    <tr>
        <th class="right-align pr">{{ user.givenName }} {{ user.familyName }}</th>
        <td>
            <i class="material-icons small pt-s pl color-blue-night">person_pin</i>
        </td>
    </tr>
    <tr>
        <th class="right-align pr">{{ user.email }}</th>
        <td>
            <i class="material-icons small pt-s pl color-blue-night">mail</i>
        </td>
    </tr>
    <tr>
        <th class="right-align pr">{{ user.telephone }}</th>
        <td>
            <i class="material-icons small pt-s pl color-blue-night">phone</i>
        </td>
    </tr>
    {% if picture %}
    <tr class="border-bottom-0">
        <th class="right-align pr">
            <a class="modal-trigger profile-link" href="#profile-picture">
                {% trans %}See my picture{% endtrans %}
            </a>
        </th>
        <td>
            <i class="material-icons small pt-s pl color-blue-night">photo</i>
        </td>
    </tr>
    {% endif %}
    </tbody>
</table>